export default{
    path:'/home',name:'主页',
    component:()=>import("../../views/home.vue"),
    children:[
        {
            path:"capacity",
            name:"智能",
            component:()=>import("../../views/home/capacity.vue")
        },
        {
            path:"discounts",
            name:"特惠",
            component:()=>import("../../views/home/discounts.vue")
        },
        {
            path:"electric",
            name:"电器",
            component:()=>import("../../views/home/electric.vue")
        },
        {
            path:"fashion",
            name:"时尚",
            component:()=>import("../../views/home/fashion.vue")
        },
        {
            path:"life",
            name:"生活",
            component:()=>import("../../views/home/life.vue")
        },
        {
            path:"recommed",
            name:"推荐",
            component:()=>import("../../views/home/recommed.vue")
        },
    ]
}